name: Onboard New Client

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  prepare:
    if: ${{ github.event.issue.title == '[Client] Onboard new client' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      company_name: ${{ steps.out.outputs.company_name }}
      company_code: ${{ steps.out.outputs.company_code }}
      location:     ${{ steps.out.outputs.location }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract values using Python
        run: |
          echo "${{ github.event.issue.body }}" | python3 scripts/extract_issue_fields.py

      - name: Debug print
        run: |
          echo "Company Name: $company_name"
          echo "Company Code: $company_code"
          echo "Location: $location"

      # Promote env vars to job outputs for the next job
      - name: Set job outputs
        id: out
        run: |
          {
            echo "company_name=$company_name"
            echo "company_code=$company_code"
            echo "location=$location"
          } >> "$GITHUB_OUTPUT"

  call-reusable:
    needs: prepare
    uses: AgentSprint/agentsprint-info-azure/.github/workflows/onboarding-new-client.yml@main
    with:
      company_name: ${{ needs.prepare.outputs.company_name }}
      company_code: ${{ needs.prepare.outputs.company_code }}
      location:     ${{ needs.prepare.outputs.location }}
      issue_details: ${{ github.event.issue.body }}
    secrets: inherit
