name: Onboard New Client

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  onboard-client:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == '[Client] Onboard new client' }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Extract values from issue body
        id: extract
        run: |
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Extract using grep/sed/awk (since body is YAML-like Markdown)
          COMPANY_NAME=$(echo "${{ github.event.issue.body }}" | grep "Company Name" -A1 | tail -n1 | xargs)
          COMPANY_CODE=$(echo "${{ github.event.issue.body }}" | grep "Company Code" -A1 | tail -n1 | xargs)
          LOCATION=$(echo "${{ github.event.issue.body }}" | grep "Location" -A1 | tail -n1 | xargs)

          echo "company_name=$COMPANY_NAME" >> $GITHUB_ENV
          echo "company_code=$COMPANY_CODE" >> $GITHUB_ENV
          echo "location=$LOCATION" >> $GITHUB_ENV

      - name: Debug print
        run: |
          echo "Company Name: ${{ env.company_name }}"
          echo "Company Code: ${{ env.company_code }}"
          echo "Location: ${{ env.location }}"