name: Onboard New Client

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  onboard-client:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == '[Client] Onboard new client' }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Extract values using Python
        run: |
          echo "${{ github.event.issue.body }}" | python3 parse_issue.py

      - name: Debug print
        run: |
          echo "Company Name: $company_name"
          echo "Company Code: $company_code"
          echo "Location: $location"